version: "1.0.0"

services:
  lacus_frontend:
    image: eyesmoons/lacus-frontend:2.0.0
    container_name: lacus_frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - lacus
    depends_on:
      - lacus_backend

  lacus_backend:
    image: eyesmoons/lacus-backend:2.0.0
    container_name: lacus_backend
    restart: always
    ports:
      - "8090:8090"
    networks:
      - lacus
    volumes:
      - ./lacus-backend/data:/data
    depends_on:
      - my_redis
      - my_mysql
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  my_redis:
    image: redis:7.4.1-alpine
    container_name: my_redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "16379:16379"
    networks:
      - lacus
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    privileged: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  my_mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=lacus
      - MYSQL_USER=shengyu
      - MYSQL_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
       - "31306:31306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - lacus
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  my_flink:
    image: eyesmoons/flink:1.16.2
    container_name: my_flink
    restart: always
    ports:
      - "8081:8081"
    command: ["bash","-c","/opt/apache/flink-1.16.2/bin/start-cluster.sh && tail -f /dev/null"]
    networks:
      - lacus
networks:
  lacus:
    driver: bridge
